### ISSUE TITLE
Call to undefined method 'configure'

### ISSUE THREAD

**Issue by fadez** [lab123it/aws-sns#2]
Every time I run artisan (Laravel 5.4) this error shows up:
`Call to undefined method Illuminate\Foundation\Application::configure()`

This is due to [this line](https://github.com/lab123it/aws-sns/blob/master/src/AwsSnsServiceProvider.php#L77).

**Comment by usulix** [comment]
@fadez, PR submitted

**Comment by jeanpfs** [comment]
@fadez This error fixed in new version;
Thanks @usulix!
