### ISSUE TITLE
I got minimum stability issues

### ISSUE THREAD

**Issue by inqtechnologies** [lab123it/aws-sns#4]
Hi,

When i try to download the files  from composer i got the minimum stability issues. Please refer this attached screenshots

![image](https://user-images.githubusercontent.com/28392686/29993313-849f1ae0-8fd1-11e7-89ba-45f2b62e58ec.png)

**Comment by jeanpfs** [comment]
Hi, sorry for my delay.

Please, use:

`composer require lab123/aws-sns:dev-master`
